// Generated by https://quicktype.io

export interface GeoJSON {
	type: string;
	name: string;
	features: Feature[];
}

export interface Feature {
	type: string;
	properties: Properties;
	geometry: Geometry;
}

export interface Geometry {
	type: string;
	coordinates: number[];
}

export interface Properties {
	TIME_24_HOURS: string;
	'BASE/SUB_BASE': string;
	COUNTY: string;
	ROAD: string;
	MV_INVOLVED: string;
	BRIEF_ACCIDENT_DETAILS: string;
	NAME_OF_VICTIM: string;
	GENDER: string;
	AGE: string;
	CAUSE_CODE: string;
	VICTIM: string;
	'NO.': string;
	DATE: string;
	DAY_OF_WEEK: string;
	LONGITUDE: number;
	LATITUDE: number;
	number: string;
	PLACE: string;
}
